# Generated by Django 3.2.5 on 2021-08-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210801_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Post',
            new_name='post',
        ),
    ]
