# Generated by Django 3.2.5 on 2021-08-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Made Request'),
        ),
    ]
